Added variable expansion to startup script and updated README

diff --git a/bin/devstartup b/bin/devstartup
--- a/bin/devstartup
+++ b/bin/devstartup
@@ -4,12 +4,23 @@
 # See https:vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
 set -Eeuxo pipefail
 
-export STRIPE_SECRET_KEY="My-secret-key"
-export STRIPE_PUBLISHABLE_KEY="My-stripe-key"
-export EMAIL_HOST_USER="HOST_USER"
-export EMAIL_HOST_PASSWORD="Password"
-export DT_TENANT_URL="https://<ENVIRONMENT_ID>.live.dynatrace.com/api/v2/otlp/v1/traces"
-export DT_API_TOKEN="<DYNATRACE_API_TOKEN>"
+# Command line options
+usage() {
+    echo "Usage: $0 (vanilla|instrument|debug)"
+}
+
+#!/bin/bash
+#
+# Stop on Errors
+# See https:vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
+set -Eeuxo pipefail
+
+export STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
+export STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
+export EMAIL_HOST_USER=${EMAIL_HOST_USER}
+export EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
+export DT_TENANT_URL=${DT_TENANT_URL}
+export DT_API_TOKEN=${DT_API_TOKEN}
 
 # Enable the following line to disable Django Auto-instrumentation with OpenTelemetry
 #export OTEL_PYTHON_DJANGO_INSTRUMENT=False
